# PostgreSQL
development:
  adapter: postgresql
  encoding: utf8
  database: golf_development
  pool: 5
  username: postgres
  password: postgres
  
production: 
  adapter: mysql
  database: golfcreo_main
  encoding: utf8
  host: localhost
  password: h.4SUWuSHHMy
  username: golfcreo_main
  
test: 
  adapter: postgresql
  encoding: utf8
  database: golf_test
  pool: 5
  username: postgres
  password: postgres

